- name: initialize the cluster
  command: kubeadm init --pod-network-cidr={{ network_prefix }}.0/24 --apiserver-advertise-address={{ master_node }}
  args:
    creates: /root/cluster_initialized.txt
  register: kubeadm_init_raw

#- name: install calico operator
#  command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/tigera-operator.yaml
#
#- name: install calico custom resources
#  command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/custom-resources.yaml
#
- name: save kubeadm init output to a file
  copy:
    content: "stdout:\n{{ kubeadm_init_raw.stdout }}\n\nstderr:\n{{ kubeadm_init_raw.stderr }}"
    dest: /root/cluster_initialized.txt
  when: kubeadm_init_raw.changed

- name: create .kube directory
  file:
    path: /home/kube/.kube
    state: directory
    mode: 0755
    owner: kube
    group: kube

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/kube/.kube/config
    remote_src: yes
    owner: kube
    group: kube
